image: node:20

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  script:
    - nohup json-server --watch db.json &
    - sleep 5
    - echo "Contents of public directory:"
    - ls public
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/

  artifacts:
    paths:
      - public
