image: node:20

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install -g json-server concurrently

pages:
  script:
    - concurrently "json-server --watch db.json" "npm run build:wait-and-build"
    - mkdir -p public
    - cp -r dist/* public/

  artifacts:
    paths:
      - public
